name: Execute_pandoc
on: [push]

env:
    EXPORTFOLDER: "export"
    LIASCRIPTFOLDER: "files"

jobs:
  Run_pandoc:
    runs-on: ubuntu-latest
    container: oehrlis/pandoc:latest

    steps:
      - name: Check dependencies (shell, pandoc)
        run: |
             cat /etc/shells
             pandoc --version
             sudo apt-get install git

      - name: Check out current repository
        uses: actions/checkout@v2
        with: 
          path: files
      
      - name: Prepare file structure
        run: |
              mkdir -p ${EXPORTFOLDER}

      - name: Run pandoc for all LiaScript files
        run: |
              dirlist=(`ls ${LIASCRIPTFOLDER}/*.md`)
              for ((i=0; i < ${#dirlist[@]}; i++)); do
                 filenameWithExtension=${dirlist[$i]##*/}
                 filename=${filenameWithExtension%%.*}
                 if [[ ${filenameWithExtension} != "README.md" ]]
                 then
                    echo ""
                    echo "================================"
                    echo "${filenameWithExtension}"
                    echo "--------------------------------"
                    mkdir -p ${EXPORTFOLDER}${filename}
                    outputPath=${EXPORTFOLDER}${filename}/${filename}
                    echo "${dirlist[$i]}"
                    pandoc --toc -N --top-level-division=chapter \
                           -H ${LIASCRIPTFOLDER}/.github/workflows/head.tex \
                           -V linkcolor:blue --listings \
                           --include-in-header=${LIASCRIPTFOLDER}/.github/workflows/listings.tex \
                           -o ${outputPath}.pdf ${dirlist[$i]}
                    git add ${outputPath}.pdf
                 fi
              done
        shell: bash

      - name: Commit changes
        run: |
             git config --local user.email "action@github.com"
             git config --local user.name "GitHub Action"
             git status
             git commit -m "Add new export version of LiaScript" || echo "No changes to commit"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
             github_token: ${{ secrets.GITHUB_TOKEN }}
             branch: main