name: Execute_pandoc
on: [push]

env:
    EXPORTFOLDER: "export/"

jobs:
  Run_pandoc:
    runs-on: ubuntu-latest
    container:
        image: docker://mirisbowring/texlive_ctan_full:2019
    steps:
      - name: Check out current repository
        uses: actions/checkout@v2

      - name: Run pandoc for all LiaScript files
        run: |
              dirlist=(`ls *.md`)
              echo "${dirlist}"
