name: Execute_pandoc
on: [push]

jobs:
  Run_pandoc:
    runs-on: ubuntu-latest
    container: pandoc/ubuntu-latex:latest

    steps:
      - name: Print shell
        run: |
             cat /etc/shells

      - name: Check out current repository
        uses: actions/checkout@v2
        with: 
          path: files
      
      - name: Illustrate the problem
        run: |
             echo "Hello World"
             dirlist=(`ls /*`)
             echo ${dirlist[@]}
        shell: bash