name: Execute_pandoc
on: [push]

env:
    EXPORTFOLDER: "export/"

jobs:
  Run_pandoc:
    runs-on: ubuntu-latest
    container:
        image: docker://pandoc/latex
    steps:
      - name: Check out current repository
        uses: actions/checkout@v2

      - name: Run pandoc for all LiaScript files
        run: |
             echo "Hello World"
             dirlist=(`ls ${prefix}*.md`)
             echo "${dirlist}"
