name: Execute_pandoc
on: [push]

jobs:
  Run_pandoc:
    runs-on: ubuntu-latest
    container: pandoc/latex:2.16

    steps:
      - name: Illustrate the problem
        run: |
             echo "Hello World"
             dirlist=(`ls *`)
        shell: bash
