name: Execute_pandoc
on: [push]

env:
    EXPORTFOLDER: "export"
    LIASCRIPTFOLDER: "files"

jobs:
  Run_pandoc:
    runs-on: ubuntu-latest
    container:
        image: docker://pandoc/latex
    steps:
      - name: Check out current repository
        uses: actions/checkout@v2
        with: 
          path: files

      - name: Prepare file structure
        run: |
              mkdir -p ${EXPORTFOLDER}

      - name: Run pandoc for all LiaScript files
        run: |
              dirlist=(`ls ${LIASCRIPTFOLDER}/*.md`)
              for ((i=0; i < ${#dirlist[@]}; i++)); do
                 filenameWithExtension=${dirlist[$i]##*/}
                 filename=${filenameWithExtension%%.*}
                 if [[ ${filenameWithExtension} != "README.md" ]]
                 then
                    echo ""
                    echo "================================"
                    echo "${filenameWithExtension}"
                    echo "--------------------------------"
                    mkdir -p ${EXPORTFOLDER}${filename}
                    outputPath=${EXPORTFOLDER}${filename}/${filename}
                 fi
              done

